### ISSUE TITLE
Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift

### ISSUE THREAD

**Issue by pk26-lab** [JakeLin/SaveTheDot#8]
I have modified the code, by adding an action to perform a segue to the "Main Menu" apart from "Try again" button after the game is over. But, when the player exits the game View controller and clicks on some other view controller, the app crashes. It gives the following error:-

    Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift
      
This is the only change that I have done:-

    func displayGameOverAlert() {
          let (title, message) = getGameOverTitleAndMessage()
          let alert = UIAlertController(title: "Game Over", message: message, preferredStyle: .alert)
          let action = UIAlertAction(title: title, style: .default,
                                 handler: { _ in
                                  self.prepareGame()
               }
          )
          let action_2 = UIAlertAction(title: "Main Menu", style: .default, handler: { _ in
                                        self.performSegue(withIdentifier: "2to1segue", sender: self)})
          alert.addAction(action)
          alert.addAction(action_2)
          self.present(alert, animated: true, completion: nil)
        }

**Comment by JakeLin** [comment]
Hey, looking at the code, I don't know what causes the problem, probably inside the destination view controller. What ViewController the segue `2to1segue` goes to?

**Comment by pkhurana2610** [comment]
Thanks for the reply, I forgot to mention that I had also changed the enemyView from UIView to UIImageView. Is this  causing an error?

      @objc func generateEnemy(timer: Timer) {
      // Generate an enemy with random position
      let screenEdge = ScreenEdge.init(rawValue: Int(arc4random_uniform(4)))
      let screenBounds = UIScreen.main.bounds
      var position: CGFloat = 0
      
      switch screenEdge! {
      case .left, .right:
        position = CGFloat(arc4random_uniform(UInt32(screenBounds.height)))
      case .top, .bottom:
        position = CGFloat(arc4random_uniform(UInt32(screenBounds.width)))
      }
      
      // Add the new enemy to the view
          
      /*
      let enemyView = UIView(frame: .zero)
      enemyView.backgroundColor = getRandomColor()
      */
      
      let enemyView = UIImageView(image: UIImage(named: "1"))
      enemyView.bounds.size = CGSize(width: radius, height: radius)
          
      switch screenEdge! {
      case .left:
          enemyView.center = CGPoint(x: 0, y: position)
      case .right:
          enemyView.center = CGPoint(x: screenBounds.width, y: position)
      case .top:
          enemyView.center = CGPoint(x: position, y: screenBounds.height)
      case .bottom:
          enemyView.center = CGPoint(x: position, y: 0)
      }
          
      view.addSubview(enemyView)
      
      // Start animation
      let duration = getEnemyDuration(enemyView: enemyView)
      let enemyAnimator = UIViewPropertyAnimator(duration: duration,
                                                 curve: .linear,
                                                 animations: { [weak self] in
                                                  if let strongSelf = self {
                                                    enemyView.center = strongSelf.playerView.center
                                                  }
        }
      )
      enemyAnimator.startAnimation()
      enemyAnimators.append(enemyAnimator)
      enemyViews.append(enemyView)
    }

**Comment by pk26-lab** [comment]
Regarding your question, "What ViewController the segue 2to1segue goes to?" The view controller is an empty view controller. I think it is something to do with "func touchesBegan" as after the game ends, and I perform a segue to some other view controller, it is still recognizing my tap on the screen and crashing by giving the above-mentioned error!
